/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Entidades.Venta;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alumno
 */
public class frmListadoVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form fmrListarVentas
     */
    public frmListadoVentas() {
        initComponents();
        
        this.llenarTablaVentas();
    }
    
    public void llenarTablaVentas(){
        DefaultTableModel modelo = new DefaultTableModel();
        tbListarVentas.setModel(modelo);

        modelo.addColumn("IdVenta");
        modelo.addColumn("Helado");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Importe");
        modelo.addColumn("Fecha");

        ArrayList<Venta> lista = Venta.listarVentas();
        Iterator iter = lista.iterator();
        Object[] columnas = new Object[5];

        try {
            while (iter.hasNext()) {
            Venta v = (Venta) iter.next();
            columnas[0] = v.getIdVenta();
            columnas[1] = v.getHelado();
            columnas[2] = v.getCantidad();
            columnas[3] = v.getImporte();
            columnas[4] = v.getFecha();

            modelo.addRow(columnas);
        }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbListarVentas = new javax.swing.JTable();

        tbListarVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbListarVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListarVentas;
    // End of variables declaration//GEN-END:variables
}
